In [1]:
import numpy as np


In [2]:
np.poly?

Signature:       np.poly(seq_of_zeros)
Call signature:  np.poly(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function poly at 0x000002C5293BDB40>
File:            c:\users\utkarsh\miniconda3\lib\site-packages\numpy\lib\polynomial.py
Docstring:      
Find the coefficients of a polynomial with the given sequence of roots.

.. note::
   This forms part of the old polynomial API. Since version 1.4, the
   new polynomial API defined in `numpy.polynomial` is preferred.
   A summary of the differences can be found in the
   :doc:`transition guide </reference/routines.polynomials>`.

Returns the coefficients of the polynomial whose leading coefficient
is one for the given sequence of zeros (multiple roots must be included
in the sequence as many times as their multiplicity; see Examples).
A square matrix (or array, which will be treated as a matrix) can also
be given, in which case the coefficients of the characteristic polynomial
of the matrix are returned.

Pa

In [6]:
x=np.array([2,3,5,1])
x2d=np.array([[1,2,3],[4,5,6]])
x3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x)
print(x2d)
print(x3d)

[2 3 5 1]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
# sequential matrix, np.arange() and np.linspace()
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [14]:
np.arange(0,10,0.2).reshape(5,10)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [21]:
a=np.linspace(0, 10, 6) # 5 evenly spaced values from 0 to 10
print(a)

[ 0.  2.  4.  6.  8. 10.]


In [22]:
np.reshape(a, (2, 3)) # reshape array a to 2 rows and 3 columns

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]])

In [23]:
np.random.rand(3, 2)

array([[0.00955347, 0.7789121 ],
       [0.81042138, 0.79627171],
       [0.19298841, 0.3510785 ]])

In [25]:
print(np.random.randint(1,7,(3,3)))

[[2 3 6]
 [3 2 1]
 [4 5 6]]


In [26]:
print(np.random.permutation([1,2,3,4,5,6,7,8,9,10]))

[ 7  8  4  9  3 10  5  2  6  1]


In [27]:
a= np.random.randint(1,10,(3,3))
b= np.random.randint(1,10,(3,3))
print(a)
print(b)

[[1 7 4]
 [7 7 3]
 [5 1 1]]
[[3 5 7]
 [6 2 3]
 [4 7 8]]


In [28]:
a*10

array([[10, 70, 40],
       [70, 70, 30],
       [50, 10, 10]])

In [29]:
a**2

array([[ 1, 49, 16],
       [49, 49,  9],
       [25,  1,  1]])

In [30]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 4 12 11]
 [13  9  6]
 [ 9  8  9]]
[[-2  2 -3]
 [ 1  5  0]
 [ 1 -6 -7]]
[[ 3 35 28]
 [42 14  9]
 [20  7  8]]
[[0.33333333 1.4        0.57142857]
 [1.16666667 3.5        1.        ]
 [1.25       0.14285714 0.125     ]]
