In [3]:
import numpy as np
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [4]:
np.linspace(0,10,2)

array([ 0., 10.])

In [5]:
np.arange(0,10,1).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
x=np.array([1,2,3])
print(x)

[1 2 3]


In [9]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
y=np.arange(1,12,2).reshape(2,3)
print(y)

[[ 1  3  5]
 [ 7  9 11]]


In [16]:
y=np.random.randint(1,10,(2,6))
print(y)

[[1 3 6 2 6 4]
 [4 3 7 9 4 4]]


In [21]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=a+b
print(c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [23]:
x=np.arange(1,12,2).reshape(2,3)
print(x)   

[[ 1  3  5]
 [ 7  9 11]]


In [28]:
z=np.linspace(1,10,6).reshape(2,3)
print(z)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [32]:
x=np.random.randint(1,10,6).reshape(2,3)
print(x)

[[2 6 8]
 [6 1 5]]


In [33]:
x=np.array([[2,6,8],[6,1,5]])
print(x)

[[2 6 8]
 [6 1 5]]


In [34]:
y=x.transpose()
print(y)

[[2 6]
 [6 1]
 [8 5]]


In [35]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [38]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [37]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [39]:
a=np.array(42)
b=np.array([1,2,3])
c=np.array([[1,2,3],[1,2,3]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [40]:
x=np.array([1,2,3,4,5])
print(x[2])

3


In [60]:
x=np.array([[1,2,3],[4,5,6]])
print(x)
print("the element at second row and third column will be: ",x[1,2])
print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[0,-1])
print(x[0,-2])
print(x[1,-3])

[[1 2 3]
 [4 5 6]]
the element at second row and third column will be:  6
1
2
4
3
2
4


In [52]:
y=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(y)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [54]:
print(y[1,1,1])

11


- Slicing

In [61]:
x=np.array([1,2,3,4,5])
print(x[1:3])

[2 3]


In [62]:
print(x[1:])

[2 3 4 5]


In [63]:
print(x[:4])

[1 2 3 4]


In [64]:
x=np.random.randint(1,10,9).reshape(3,3)
print(x)

[[5 1 9]
 [2 5 7]
 [4 5 2]]


In [69]:
x=np.random.randint(1,10,9).reshape(3,3)
print(x)


[[9 3 8]
 [1 6 6]
 [1 9 1]]


In [70]:
print(x[1:3,1:3])

[[6 6]
 [9 1]]


In [71]:
print(x[0:,1:])

[[3 8]
 [6 6]
 [9 1]]


In [72]:
print(x[1:,:])

[[1 6 6]
 [1 9 1]]


In [73]:
print(x[1:,:2])

[[1 6]
 [1 9]]


In [74]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [75]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int32


In [77]:
arr=np.array([[1.2,2.3,3.4],[4.4,5.5,2.6]])
print(arr.dtype)

float64


In [79]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(arr.dtype)

['apple' 'banana' 'cherry']
<U6


In [80]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [82]:
arr = np.array([1, 2, 3, 4], dtype='int16')

print(arr)
print(arr.dtype)

[1 2 3 4]
int16


In [83]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [84]:
arr=np.array([1.2,2.3,3.4,4.5,5.6], dtype='int32')
print(arr)

[1 2 3 4 5]


In [85]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [86]:
arr=np.array([1,2,0,0,4,5,0], dtype=bool)
print(arr)

[ True  True False False  True  True False]


In [87]:
arr=np.random.randint(1,10,(3,4))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)


[[9 9 4 7]
 [5 3 3 1]
 [8 3 7 4]]
(3, 4)
2
12
int32
4
48


In [96]:
a=np.arange(1,10,1)
print(a)
b=np.arange(11,20,1)
print(b)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [97]:
a1=a.reshape(3,3)
print(a1)
b1=b.reshape(3,3)
print(b1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [99]:
c1=np.matmul(a1,b1)
print(c1)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [100]:
print(c1.shape)
print(c1.size)

(3, 3)
9


In [101]:
print(c1.T)

[[ 90 216 342]
 [ 96 231 366]
 [102 246 390]]


In [103]:
zero=np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


one=np.ones((3,4))
print(one)

In [108]:
emp1=np.empty((3,4))
print(emp1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [118]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ravel())
print(arr.flatten())
print(arr)
print(arr.argmax())
print(arr.argmin())
print("Argsort")
print(arr.argsort())
print("argsort axis=0")
print(arr.argsort(axis=0))
print("argsort axis=1")
print(arr.argsort(axis=1))
print(arr.reshape(3,2))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
5
0
Argsort
[[0 1 2]
 [0 1 2]]
argsort axis=0
[[0 0 0]
 [1 1 1]]
argsort axis=1
[[0 1 2]
 [0 1 2]]
[[1 2]
 [3 4]
 [5 6]]


In [114]:
arr=np.random.randint(1,10,(4,4))
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[8 8 3 6]
 [8 1 8 7]
 [2 3 5 2]
 [7 5 9 8]]
[25 17 25 23]
[25 24 12 29]


In [121]:
arr=np.array([[1,3,2],[4,7,6],[7,10,9]])
print(arr)

[[ 1  3  2]
 [ 4  7  6]
 [ 7 10  9]]


In [122]:
print(arr.argsort())

[[0 2 1]
 [0 2 1]
 [0 2 1]]


In [123]:
print(arr.argmax())

7


In [124]:
print(arr.argsort(axis=0))

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [125]:
print(arr.argsort(axis=1))

[[0 2 1]
 [0 2 1]
 [0 2 1]]


In [128]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sqrt(arr))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [129]:
print(arr.sum())

45


In [130]:
print(arr.max())

9


In [131]:
print(arr.argmax())

8


In [136]:
arr=np.random.randint(1,12,(10,10))
print(arr)
print("first row")
print(arr[0,:])
print("first column")
print(arr[:,0])
print("first 3 rows")
print(arr[0:3,:])
print("first 3 columns")
print(arr[:,0:3])

[[11  3  3  5  8  4  1  5  6 10]
 [ 3  2  7  1  4  4 11  3  9 10]
 [ 2 11 10  9  9 11  8 11  4  2]
 [ 2  7 11  4  6  1  7  4  6  4]
 [ 6  4  8  8 11  1  2  9 11  7]
 [ 2  5  3  2  9  7  7  9  3  4]
 [ 2  7  9  1 10  5  1 11 11  7]
 [11  3  5  5  9  3  9  5  2  5]
 [11  6 10 10 11 11  6  9  7  8]
 [10  2  3  5 11  7  7  4  4  2]]
first row
[11  3  3  5  8  4  1  5  6 10]
first column
[11  3  2  2  6  2  2 11 11 10]
first 3 rows
[[11  3  3  5  8  4  1  5  6 10]
 [ 3  2  7  1  4  4 11  3  9 10]
 [ 2 11 10  9  9 11  8 11  4  2]]
first 3 columns
[[11  3  3]
 [ 3  2  7]
 [ 2 11 10]
 [ 2  7 11]
 [ 6  4  8]
 [ 2  5  3]
 [ 2  7  9]
 [11  3  5]
 [11  6 10]
 [10  2  3]]


In [138]:
z1=np.random.randint(1,10,(3,4))
z2=np.random.randint(1,10,(3,4))
print(np.vstack((z1,z2)))

[[2 6 5 4]
 [2 1 6 2]
 [7 7 8 6]
 [5 8 4 6]
 [5 9 8 4]
 [3 9 2 1]]


In [141]:
print(np.hstack((z1,z2)))

[[2 6 5 4 5 8 4 6]
 [2 1 6 2 5 9 8 4]
 [7 7 8 6 3 9 2 1]]
